### ISSUE TITLE
Document: lack of Community Standards 

### ISSUE THREAD

**Issue by fliklab** [YOCOING/YOCO#59]
### Description

Some of document recommended as [Community Standard ](https://github.com/YOCOING/YOCO/community)is missing in this repo. It would be better to fill them.

Here are the missing items regarding the lack of Community Standards in the repository:

#### Missing Code of Conduct
- A Code of Conduct is essential as it outlines expected behaviors and promotes a respectful and inclusive environment for all contributors.

#### Missing Security Policy
- A Security Policy is crucial as it provides guidelines for reporting and handling security vulnerabilities, ensuring the repository's safety and integrity.

#### Repository Admins Do Not Accept Content Reports
- Allowing admins to accept content reports is important as it enables the community to flag and address inappropriate or harmful content, maintaining the quality and safety of the repository. (부적절한 콘텐츠, 어뷰징 등에 대해서 일반 유저가 신고할 수 있도록 허용하는 항목입니다.)

### Summary

Some of document recommended as [Community Standard ](https://github.com/YOCOING/YOCO/community)is missing.

**Comment by givvemee** [comment]
@fliklab 좋은 생각입니다만, 리서치를 찾아본 결과 내용이 대부분 레포지토리 바이 레포지토리로 다 다르더라고요. 대부분의 문서들이 포함하는 내용으로 리서치 다같이 진행한 뒤에 올릴 내용 의논하도록 하지요... cc. @glassk

**Comment by givvemee** [comment]
We are closing this issue temporarily as it is not urgently needed at the moment.
